name: Check links

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  links:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Validate links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --max-retries 3
            --accept 100..=103,200..=299,403
            './**/*.md'
          format: markdown
          output: ./lychee/out.md
          jobSummary: true
          fail: true

      - name: Upload link report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: link-check-report
          path: lychee/out.md
          if-no-files-found: error
